export const EmailTemplate = {
    VERIFICATION_SUCCESS: ['REQUEST_ID', 'DataSubjectName', 'TypeOfRequest', 'RejectionReason', 'ProcessingDays'],
    VERIFICATION_REJECT: ['REQUEST_ID', 'DataSubjectName', 'TypeOfRequest', 'RejectionReason'],
}

export enum EmailTemplateId {
    ACKNOWLEDGEMENT_OF_RECEIPT = 'ACKNOWLEDGEMENT_OF_RECEIPT',
    ACCEPTANCE_OF_REQUEST = 'ACCEPTANCE_OF_REQUEST',
    REJECTION_OF_REQUEST = 'REJECTION_OF_REQUEST',
    IDENTITY_VERIFICATION_NEEDED = 'IDENTITY_VERIFICATION_NEEDED',
    CANCELLATION_OF_REQUEST = 'CANCELLATION_OF_REQUEST',
    ADDITIONAL_DETAILS_NEEDED = 'ADDITIONAL_DETAILS_NEEDED',
    REQUEST_FOR_ADDITIONAL_TIME = 'REQUEST_FOR_ADDITIONAL_TIME',
    FEE_NOTICE = 'FEE_NOTICE',
    REQUEST_VALIDATION_CONFIRMATION = 'REQUEST_VALIDATION_CONFIRMATION',
    PARTIAL_FULFILMENT = 'PARTIAL_FULFILMENT',
    REQUEST_COMPLETION_NOTICE = 'REQUEST_COMPLETION_NOTICE',
    HUMAN_REVIEW_OF_AUTOMATION = 'HUMAN_REVIEW_OF_AUTOMATION',
    NOMINATION_COMPLETION_NOTICE = 'NOMINATION_COMPLETION_NOTICE',
    GRIEVANCE_RESOLUTION = 'GRIEVANCE_RESOLUTION',
    PROCESSOR_DATA_ACTION_REQUIRED = 'PROCESSOR_DATA_ACTION_REQUIRED',
    NEW_USER_ACCOUNT_CREATION = 'NEW_USER_ACCOUNT_CREATION',
    NEW_TASK_ASSIGNMENT = 'NEW_TASK_ASSIGNMENT',
    NEW_COMMENT_NOTIFICATION = 'NEW_COMMENT_NOTIFICATION',
    ESCALATED_REQUEST_NOTIFICATION = 'ESCALATED_REQUEST_NOTIFICATION',
    SLA_BREACH_ALERT = 'SLA_BREACH_ALERT',
    NEW_REQUEST_ASSIGNED_BY_ADMIN = 'NEW_REQUEST_ASSIGNED_BY_ADMIN',
    ADMIN_REQUEST_CANCELLATION_NOTICE = 'ADMIN_REQUEST_CANCELLATION_NOTICE',
    DOCUMENTS_UPLOADED_NOTICE = 'DOCUMENTS_UPLOADED_NOTICE',
    DATA_SUBJECT_RESPONSE_NOTICE = 'DATA_SUBJECT_RESPONSE_NOTICE',
    REQUEST_CLOSURE_NOTICE = 'REQUEST_CLOSURE_NOTICE'
}


export const openTemplateVariables = ['test']


export enum EmailTriggerEvent {
    DSR_DS_LOGIN_ATTEMPTED = 'dsr.ds.login.attempted',

    DSR_REQUEST_RAISED = 'dsr.request.raised',
    DSR_REQUEST_ASSIGNED = 'dsr.request.assigned',
    DSR_REQUEST_DS_IDENTITY_VERIFIED = 'dsr.request.ds-identity-verified',
    DSR_REQUEST_REJECTED = 'dsr.request.rejected',
    DSR_REQUEST_VALIDATED = 'dsr.request.validated',
    DSR_REQUEST_DATA_MAPPING_COMPLETED = 'dsr.request.data-mapping-completed',
    DSR_REQUEST_FULFILLED = 'dsr.request.fulfilled',
    DSR_REQUEST_CLOSED = 'dsr.request.closed',
    DSR_REQUEST_CANCELLED = 'dsr.request.cancelled',
    DSR_REQUEST_EXPIRED = 'dsr.request.expired',
    DSR_REQUEST_DEADLINE_EXTENDED = 'dsr.request.deadline.extended',
    DSR_REQUEST_ASSIGNEE_UPDATED = 'dsr.request.assignee.updated',
    DSR_REQUEST_CONVERSATION_SENT = 'dsr.request.conversation.sent',

    TASK_ASSIGNED = 'task.assigned',
    TASK_COMPLETED = 'task.completed',
    TASK_ASSIGNEE_UPDATED = 'task.assignee.updated',
    TASK_CONVERSATION_SENT = 'task.conversation.sent',
}