
export const ENTITY_TYPES = {
  TASK_MANAGEMENT: 'TASK_MANAGEMENT',
  TASK: 'TASK',
  REQUEST_MANAGEMENT: 'REQUEST_MANAGEMENT',
  DATA_DISCOVERY: 'DATA_DISCOVERY',
  ASSESSMENT: 'ASSESSMENT',
  VENDORS_ASSESSMENTS: 'VENDORS_ASSESSMENTS',
  CONSENT_MANAGEMENT: 'CONSENT_MANAGEMENT',
  BPA: 'BPA',
  ASSET: 'ASSET',
  VENDOR: 'VENDOR',
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  ROLE_MANAGEMENT: 'ROLE_MANAGEMENT',
  DEPARTMENT_MANAGEMENT: 'DEPARTMENT_MANAGEMENT',
  COUNTRY_MANAGEMENT: 'COUNTRY_MANAGEMENT',
  CONFIGURATION: 'CONFIGURATION',
  DSRR:'DSR',
  ASSESSMENT_TASK: 'ASSESSMENT_TASK',
  VENDOR_ASSESSMENT_TASK: 'VENDOR_ASSESSMENT_TASK',
  QUESTION_AND_RESPONSE: 'QUESTION_AND_RESPONSE',
  VENDOR_QUESTION_AND_RESPONSE: 'VENDOR_QUESTION_AND_RESPONSE'
} as const;

export type EntityType = typeof ENTITY_TYPES[keyof typeof ENTITY_TYPES];
