// Permission Constants
export enum UserPrimitives {

    // --- DSR ---
    CREATE_DSR_REQUEST = "DSR::DATA_SUBJECT_REQUEST::ROW::CREATE",
    EDIT_DSR_REQUEST = "DSR::DATA_SUBJECT_REQUEST::ROW::EDIT",
    VIEW_ALL_DSR_REQUEST = "DSR::DATA_SUBJECT_REQUEST::ROW::VIEW_ALL",
    AUTO_ASSIGN_DSR_REQUEST = "DSR::DATA_SUBJECT_REQUEST::ROW::AUTO_ASSIGN",
    FULL_ACCESS_DSR_REQUEST = "DSR::DATA_SUBJECT_REQUEST::FEATURE::FULL_ACCESS",
    VIEW_DSR_FEATURE = "DSR::DATA_SUBJECT_REQUEST::FEATURE::VIEW",
    CREATE_TASK_REQUEST = "DSR::DATA_SUBJECT_REQUEST::FEATURE::TASK_CREATE",
    DSR_EXPORT = "DSR::DATA_SUBJECT_REQUEST::FEATURE::EXPORT",
    // -- DSR TASK --
    DSR_TASK = "DSR::TASK::FEATURE::VIEW",
    // --- BPA ---
    CREATE_BPA = "DATA_DISCOVERY::BPA::ROW::CREATE",
    EDIT_BPA = "DATA_DISCOVERY::BPA::ROW::EDIT",
    FULL_ACCESS_BPA = "DATA_DISCOVERY::BPA::FEATURE::FULL_ACCESS",
    VIEW_BPA = "DATA_DISCOVERY::BPA::FEATURE::VIEW",

    // ---Asset ---
    VIEW_ASSET = "DATA_DISCOVERY::ASSET::FEATURE::VIEW",
    CREATE_ASSET = "DATA_DISCOVERY::ASSET::ROW::CREATE",
    EDIT_ASSET = "DATA_DISCOVERY::ASSET::ROW::EDIT",
    FULL_ACCESS_ASSET = "DATA_DISCOVERY::ASSET::FEATURE::FULL_ACCESS",

    // --- Inventory ---
    VIEW_INVENTORY = "DATA_DISCOVERY::INVENTORY::FEATURE::VIEW",
    IMPORT_INVENTORY = "DATA_DISCOVERY::INVENTORY::ROW::IMPORT",
    VIEW_CP = "DATA_DISCOVERY::CP::FEATURE::VIEW",

    // --- Auth User ---
    VIEW_AUTH_USER = "AUTH::USER::FEATURE::VIEW",
    CREATE_AUTH_USER = "AUTH::USER::ROW::CREATE",
    EDIT_AUTH_USER = "AUTH::USER::ROW::EDIT",
    FULL_ACCESS_AUTH_USER = "AUTH::USER::FEATURE::FULL_ACCESS",

    // --- Auth Role ---
    VIEW_AUTH_ROLE = "AUTH::ROLE::FEATURE::VIEW",
    CREATE_AUTH_ROLE = "AUTH::ROLE::ROW::CREATE",
    EDIT_AUTH_ROLE = "AUTH::ROLE::ROW::EDIT",
    FULL_ACCESS_AUTH_ROLE = "AUTH::ROLE::FEATURE::FULL_ACCESS",

    // --- Auth Module ---
    FULL_ACCESS_AUTH = "AUTH::FEATURE::FULL_ACCESS",

    // --- Configuration ---
    FULL_ACCESS_CONFIGURATION = "CONFIGURATION::FEATURE::FULL_ACCESS",

    // --- Template ---
    CREATE_ASSESSMENT_TEMPLATE = "ASSESSMENT::TEMPLATE::ROW::CREATE",
    EDIT_ASSESSMENT_TEMPLATE = "ASSESSMENT::TEMPLATE::ROW::EDIT",
    VIEW_ASSESSMENT_TEMPLATE = "ASSESSMENT::TEMPLATE::FEATURE::VIEW",
    FULL_ACCESS_ASSESSMENT_TEMPLATE = "ASSESSMENT::TEMPLATE::FEATURE::FULL_ACCESS",

    // --- Assessment ---
    CREATE_ASSESSMENT_INSTANCE = "ASSESSMENT::INSTANCE::ROW::CREATE",
    EDIT_ASSESSMENT_INSTANCE = "ASSESSMENT::INSTANCE::ROW::EDIT",
    APPROVE_ASSESSMENT_INSTANCE = "ASSESSMENT::INSTANCE::ROW::APPROVE",
    VIEW_ALL_ASSESSMENT_INSTANCE = "ASSESSMENT::INSTANCE::ROW::VIEW_ALL",
    VIEW_ASSESSMENT_INSTANCE = "ASSESSMENT::INSTANCE::FEATURE::VIEW",
    FULL_ACCESS_ASSESSMENT_INSTANCE = "ASSESSMENT::INSTANCE::FEATURE::FULL_ACCESS",
    FULL_ACCESS_ASSESSMENT = "ASSESSMENT::FEATURE::FULL_ACCESS",
    ASSESSMENT_TASK_VIEW = "ASSESSMENT::TASK::FEATURE::VIEW",

    // --- Vendor ---
    VIEW_VENDOR = "VENDOR::VENDOR_RECORD::FEATURE::VIEW",
    CREATE_VENDOR = "VENDOR::VENDOR_RECORD::ROW::CREATE",
    EDIT_VENDOR = "VENDOR::VENDOR_RECORD::ROW::EDIT",

    VIEW_VENDOR_TEMPLATE = "VENDOR::TEMPLATE::FEATURE::VIEW",
    EDIT_VENDOR_TEMPLATE = "VENDOR::TEMPLATE::ROW::EDIT",
    FULL_ACCESS_VENDOR_TEMPLATE = "VENDOR::TEMPLATE::FEATURE::FULL_ACCESS",

    VIEW_VENDOR_ASSESSMENT = "VENDOR::ASSESSMENT::FEATURE::VIEW",
    CREATE_VENDOR_ASSESSMENT = "VENDOR::ASSESSMENT::ROW::CREATE",
    EDIT_VENDOR_ASSESSMENT = "VENDOR::ASSESSMENT::ROW::EDIT",
    VIEW_ALL_VENDOR_ASSESSMENT = "VENDOR::ASSESSMENT::ROW::VIEW_ALL",
    APPROVE_VENDOR_ASSESSMENT = "VENDOR::ASSESSMENT::ROW::APPROVE",
    FULL_ACCESS_VENDOR_ASSESSMENT = "VENDOR::ASSESSMENT::FEATURE::FULL_ACCESS",
    FULL_ACCESS_VENDOR = "VENDOR::FEATURE::FULL_ACCESS",
    VENDOR_ASSESSMENT_TASK_VIEW = "VENDOR::ASSESSMENT_TASK::FEATURE::VIEW",
}

export const FEATURE_FULL_ACCESS = "FULL_ACCESS"