export const routes = {
  LOGIN: 'login',
  EXTERNAL_LOGIN: 'external-login',
  INTERNAL_LOGIN: 'internal-login',
  RESET_PASSWORD: 'reset-password',
  INVITE_RESET_PASSWORD: 'invite-reset-password',
  USER: 'user',
  ADMIN: 'admin',
  DASHBOARD: 'dashboard',
  NOT_FOUND: 'not-found',
  CREATE_TEMPLATE: 'create',
  PREVIEW_TEMPLATE: 'preview',
  TEMPLATE_LIST: 'list',
  TEMPLATE_DETAILS: 'details',
  DOWNLOAD: 'download',
  DOWNLOAD_LIST: 'list',
  SSO_AUTH: 'sso-auth',
  SSO_EXTERNAL_AUTH: "sso-external-auth",
  SSO_INTERNAL_AUTH: "sso-internal-auth",
  DSRR: 'dsrr',
  REQUEST_MANAGEMENT: 'request',
  REQUEST_MANAGEMENT_LIST: 'list',
  CREATE_REQUEST_MANAGEMENT: 'create',
  REQUEST_MANAGEMENT_DETAILS: 'details',
  REQUEST_TASK_MANAGEMENT_DETAILS: 'task-details',

  CONSENT_MANAGEMENT: 'consent-management',
  CONSENT_MANAGEMENT_PURPOSE: 'consent-management-purpose',
  CONSENT_MANAGEMENT_TEMPLATES: 'consent-management-templates',
  CONSENT_MANAGEMENT_FORMS: 'consent-management-forms',
  CONSENT_MANAGEMENT_RECORDS: 'consent-management-records',

  USER_MANAGEMENT: 'users',
  USER_MANAGEMENT_LISTING: 'list',
  USER_MANAGEMENT_CREATION: 'create',
  USER_MANAGEMENT_DETAILS: 'details',
  USER_MANAGEMENT_ASSIGN: 'assign-role',
  ROLE_MANAGEMENT: 'roles',
  ROLE_MANAGEMENT_LISTING: 'list',
  ROLE_MANAGEMENT_CREATION: 'create',
  ROLE_MANAGEMENT_DETAILS: 'details',

  IDP_CONFIGURATION: 'idp',
  IDP_CONFIGURATION_LISTING: 'idp',
  DEPARTMENT_MANAGEMENT: 'departments',
  DEPARTMENT_MANAGEMENT_LISTING: 'list',
  DEPARTMENT_MANAGEMENT_CREATION: 'create',
  DEPARTMENT_MANAGEMENT_DETAILS: 'details',
  COUNTRY_MANAGEMENT: 'countries',
  COUNTRY_MANAGEMENT_LISTING: 'list',
  COUNTRY_MANAGEMENT_CREATION: 'create',
  COUNTRY_MANAGEMENT_DETAILS: 'details',

  TASK_MANAGEMENT: 'task',
  TASK_MANAGEMENT_LIST: 'list',
  TASK_MANAGEMENT_DETAILS: 'details',

  CONSENT_MANAGEMENT_LIST: 'list',
  CONSENT_MANAGEMENT_CREATE: 'create',
  CONSENT_MANAGEMENT_PREVIEW: 'preview',
  CONSENT_MANAGEMENT_DETAILS: 'details',
  CONSENT_TERM_PAGE: 'term',
  REQUEST_DATA_SUBJECT_DETAILS: 'request-managements-data',
  DSR_FORM: 'dsr-form',
  BUSINESS_PROCESSING_ACTIVITIES: 'business-processing-activities',
  USER_PROFILE: 'profile',
  CONFIGURATION: 'configuration',
  REGULATION: 'regulation',
  EMAIL_CONFIGURATION: 'email-configuration',
  EMAIL_CONFIGURATION_LIST: 'list',
  EMAIL_CONFIGURATION_CREATE: 'create',
  ERROR_404: 'error-404',
  BAD_NETWORK: 'bad-network',
  ITEM_NOT_FOUND: 'item-not-found',
  WITHDRAW_CONSENT: 'withdraw-consent',
  CONSENT_DETAILS: 'consent-details',
  DATA_SUBJECT_DETAILS: 'data-subject',
  CONSENT_ASSETS: 'assets',
  CONSENT_ASSETS_LIST: 'list',
  CREATE_ASSETS: 'create',
  ASSETS_DETAILS: 'details',
  DATA_DISCOVERY: 'data-discovery',
  BPA: 'bpa',
  COLLECTION_POINT: 'collection-point',
  COLLECTION_POINT_LIST: 'list',
  COLLECTION_POINT_DETAILS: 'details',
  BPA_LIST: 'list',
  BPA_CREATE: 'create',
  BPA_DETAILS: 'details',
  BPA_DFD_DETAILS: 'bpa-dfd-details',
  DATA_INVENTORY: 'data-inventory',
  CREATE_DATA_INVENTORY: 'create-data-inventory',

  CONFIG_DATA_INVENTORY: 'data-inventory',
  CONFIG_DATA_INVENTORY_LIST: 'list',
  CATEGORY_DETAILS: 'category-details',
  FORM_CONFIG: 'form-configuration',
  REGULATION_LIST: 'list',
  FORM_CONFIG_CREATE: 'detail',
  FORM_CONFIG_PREVIEW: 'preview',
  ASSESSMENTS: 'assessments',
  ASSESSMENT: 'assessment',
  RISK: 'risks',

  TEMPLATES: 'templates',
  ASSESSMENT_QUESTIONS_LIST: 'list',
  CREATE_DPIA_ASSESSMENT: 'create',
  CREATE_ASSESSMENT: 'create',
  ASSESSMENT_DETAILS: 'details',
  CREATE_ASSESSMENT_QUESTIONS: 'create',
  MITIGATION_APPROVE: 'mitigation-approve',

  ASSESSMENT_TASKS_LIST: 'tasks',
  ASSESSMENT_TASK: 'task',
  ASSESSMENT_RISK: 'risk',

  VENDORS: 'vendors',
  VENDOR: 'vendor',
  VENDORS_LIST: 'list',
  VENDORS_DETAILS: 'vendors-details',
  VENDORS_CREATE: 'Create',
  CREATE_VENDOR_RECORD: 'create-vendor',

  CRAETE_REGULATION: 'create',
  REGULATION_CREATE: 'create',
  REGULATION_DETAILS: 'details',
  DECLARATION_DETAILS: 'declaration-details',
  DOWNLOAD_LAYOUT: 'download-layout',
  GENERAL_CONFIGURATION: 'general',
  GENERAL_CONFIGURATION_LIST: 'list'

}

export const routesName = {
  DASHBOARD: 'Dashboard',
  REQUEST_MANAGEMENT: 'Requests',
  DSRR: 'DSR Management',
  CREATE_REQUEST_MANAGEMENT: 'Create',
  REQUEST_MANAGEMENT_DETAILS: 'Details',
  IDP_CONFIGURATION: 'idp',
  IDP_CONFIGURATION_LISTING: 'IDP',
  CONSENT_MANAGEMENT: 'Consent Management',
  CONSENT_MANAGEMENT_CREATE: 'Create',
  CONSENT_MANAGEMENT_PREVIEW: 'Preview',
  CONSENT_MANAGEMENT_DETAILS: 'Details',
  CONSENT_MANAGEMENT_PURPOSE: 'Consent Purpose',
  CONSENT_MANAGEMENT_TEMPLATES: 'Consent Templates',
  CONSENT_MANAGEMENT_FORMS: 'Consent Forms',
  CONSENT_MANAGEMENT_RECORDS: 'Consent Records',
  CONSENT_MANAGEMENT_TERM_PAGE: 'Term',
  RISK: 'Risk & Measures',

  BUSINESS_PROCESSING_ACTIVITIES: 'Processing Activity',
  USER_PROFILE: 'User Profile',
  CONFIGURATION_MODULE: 'Configuration Module',
  ERROR_404: 'Error 404',
  BAD_NETWORK: 'Bad Network',
  ITEM_NOT_FOUND: 'Item Not Found',
  WITHDRAW_CONSENT: 'Withdraw Consent',
  DATA_SUBJECT_DETAILS: 'Details',

  CONSENT_ASSETS: 'Asset',
  CREATE_ASSETS: 'Create',
  ASSETS_DETAILS: 'Details',
  DATA_DISCOVERY: 'Data Discovery',
  BPA_CREATE: 'Create',
  CREATE_TEMPLATE: 'Create',
  PREVIEW_TEMPLATE: 'Preview',
  TEMPLATES: 'Templates',
  TEMPLATE_LIST: 'List',
  TEMPLATE_DETAILS: 'Details',
  BPA: 'Processing Activity',
  BPA_LIST: 'List',
  BPA_DETAILS: 'Details',
  COLLECTION_POINT: 'Collection Point',
  COLLECTION_POINT_LIST: 'List',
  COLLECTION_POINT_DETAILS: 'Details',
  DATA_INVENTORY: 'data inventory',
  CREATE_DATA_INVENTORY: 'craete data inventory',
  UPDATE_PAYMENT_FORM: 'update password',
  REQUEST_DATA_SUBJECT_DETAILS: 'Request Managements Data',
  TASK_MANAGEMENT: 'Task Management',
  TASK_MANAGEMENT_LIST: 'Task List',
  TASK_MANAGEMENT_DETAILS: 'Details',
  USER_MANAGEMENT: 'Users',
  USER_MANAGEMENT_LISTING: 'Users',
  USER_MANAGEMENT_CREATION: 'Create',
  USER_MANAGEMENT_DETAILS: 'Details',
  USER_MANAGEMENT_ASSIGN: 'Assign role',
  ROLE_MANAGEMENT_LISTING: 'Roles',
  ROLE_MANAGEMENT_CREATION: 'Create',
  ROLE_MANAGEMENT_DETAILS: 'Details',
  DEPARTMENT_MANAGEMENT_LISTING: 'Departments',
  DEPARTMENT_MANAGEMENT_CREATION: 'Create',
  DEPARTMENT_MANAGEMENT_DETAILS: 'Details',
  COUNTRY_MANAGEMENT_LISTING: 'Countries',
  COUNTRY_MANAGEMENT_CREATION: 'Create',
  COUNTRY_MANAGEMENT_DETAILS: 'Details',

  CONFIG_DATA_INVENTORY: 'Data inventory',
  CONFIG_DATA_INVENTORY_LIST: 'List',
  CATEGORY_DETAILS: 'Details',
  FORM_CONFIG: 'Form Configuration',
  FORM_CONFIG_PREVIEW: 'Form Preview',
  REGULATION_LIST: 'List',
  EMAIL_CONFIGURATION_LIST: 'List',
  EMAIL_CONFIGURATION_CREATE: 'Create',


  ASSESSMENT_QUESTIONS: 'Assessments',
  ASSESSMENT_QUESTIONS_LIST: 'List',
  CREATE_ASSESSMENT_QUESTIONS: 'Create',

  CREATE_DPIA_ASSESSMENT: 'Create',
  CREATE_ASSESSMENT: 'Create',
  ASSESSMENT_DETAILS: 'Details',

  ASSESSMENT_TASKS: 'Tasks',
  ASSESSMENT_TASKS_LIST: 'List',

  VENDORS: 'Vendor Record',
  VENDORS_LIST: 'List',
  VENDORS_DETAILS: 'Details',
  VENDORS_CREATE: 'Create',
  CREATE_VENDOR_RECORD: 'Create',
  REGULATION_CREATE: 'Create',
  REGULATION_DETAILS: 'Details',
  DECLARATION_DETAILS: 'Details',
  DOWNLOAD: 'Report',
  DOWNLOAD_LIST: 'list',
  GENERAL_CONFIGURATION: 'General Configuration',
  REGULATION_CONFIGURATION: 'Regulation Configuration',
  EMAIL_CONFIGURATION: 'Email Configuration',
}

export const externalWindowRoute = {
  DATA_INVENTORY_POP_UP: 'data-inventory-popup',
  REGULATION_CREATE: 'Create',
  REGULATION_DETAILS: 'Details'
}
